/**
 * This code is generated by apibrew.io. Please do not modify this file.
 */

class BookResource:
    resource = "Book"
    namespace = "default"

# Resource and Property Names
BookName = "Book"
BookIdName = "Id"
BookTitleName = "Title"
BookDescriptionName = "Description"
BookVersionName = "Version"
