/**
 * This code is generated by apibrew.io. Please do not modify this file.
 */

export const BookResource = {
    resource: "Book",
    namespace: "default",
};

// Sub Types

// Resource Type
export interface Book {
    id: string;
title: string;
description?: string;
version: number;

}
// Resource and Property Names
export const BookName = "Book";

export const BookIdName = "Id";

export const BookTitleName = "Title";

export const BookDescriptionName = "Description";

export const BookVersionName = "Version";


